name: CALCULATIONS_CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'celsius-heroku-demo' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registory.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
